# Generated by Django 4.0.4 on 2023-12-24 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_subscription', models.BooleanField()),
            ],
            options={
                'ordering': ['fitness_user__full_name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employment_history_book_id', models.CharField(blank=True, max_length=7, null=True)),
            ],
            options={
                'ordering': ['position', 'fitness_user__full_name'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название должности', max_length=255)),
                ('salary', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=500, unique=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('cost', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['program_name'],
            },
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('fitness_employee', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='common.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_name', models.CharField(max_length=500)),
                ('workout_description', models.CharField(blank=True, max_length=1000, null=True)),
                ('workout_datetime', models.DateTimeField(blank=True, null=True)),
                ('client', models.ManyToManyField(to='common.client')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='common.program')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.trainer')),
            ],
            options={
                'ordering': ['program', 'workout_name'],
            },
        ),
        migrations.CreateModel(
            name='FitnessUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.CharField(blank=True, default='', max_length=70, null=True)),
                ('gender', models.CharField(blank=True, choices=[('м', 'Мужской'), ('ж', 'Женский'), ('н', 'Не указано')], default='н', max_length=1)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='fitness_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='common.fitnessuser'),
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='common.position'),
        ),
        migrations.AddField(
            model_name='client',
            name='fitness_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='common.fitnessuser'),
        ),
    ]
