# Generated by Django 4.0.4 on 2023-12-24 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='program',
            old_name='program_name',
            new_name='name',
        ),
    ]
