# Generated by Django 4.0.4 on 2023-12-24 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_program_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitnessuser',
            name='email',
        ),
    ]
