# Generated by Django 4.0.4 on 2023-12-24 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_fitnessuser_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='workout',
            name='client',
            field=models.ManyToManyField(blank=True, null=True, to='common.client'),
        ),
    ]
