# Generated by Django 4.0.4 on 2023-12-26 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_position_options_alter_workout_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='client',
            field=models.ManyToManyField(blank=True, to='common.client'),
        ),
    ]
